/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as MatchEventIdRouteImport } from './routes/match.$eventId'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeriesRoute,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/$seriesId',
  path: '/$seriesId',
  getParentRoute: () => SeriesRoute,
} as any)
const MatchEventIdRoute = MatchEventIdRouteImport.update({
  id: '/match/$eventId',
  path: '/match/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/series': typeof SeriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/match/$eventId': typeof MatchEventIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/match/$eventId': typeof MatchEventIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/series': typeof SeriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/upcoming': typeof UpcomingRoute
  '/match/$eventId': typeof MatchEventIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/live'
    | '/privacy'
    | '/recent'
    | '/series'
    | '/terms'
    | '/upcoming'
    | '/match/$eventId'
    | '/series/$seriesId'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/live'
    | '/privacy'
    | '/recent'
    | '/terms'
    | '/upcoming'
    | '/match/$eventId'
    | '/series/$seriesId'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/how-it-works'
    | '/live'
    | '/privacy'
    | '/recent'
    | '/series'
    | '/terms'
    | '/upcoming'
    | '/match/$eventId'
    | '/series/$seriesId'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LiveRoute: typeof LiveRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentRoute: typeof RecentRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  TermsRoute: typeof TermsRoute
  UpcomingRoute: typeof UpcomingRoute
  MatchEventIdRoute: typeof MatchEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/match/$eventId': {
      id: '/match/$eventId'
      path: '/match/$eventId'
      fullPath: '/match/$eventId'
      preLoaderRoute: typeof MatchEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SeriesRouteChildren {
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowItWorksRoute: HowItWorksRoute,
  LiveRoute: LiveRoute,
  PrivacyRoute: PrivacyRoute,
  RecentRoute: RecentRoute,
  SeriesRoute: SeriesRouteWithChildren,
  TermsRoute: TermsRoute,
  UpcomingRoute: UpcomingRoute,
  MatchEventIdRoute: MatchEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
